### ISSUE TITLE
AttributeError: 'TableFileLoaderFactory' object has no attribute 'create_from_file_path'

### ISSUE THREAD

**Issue by josmos** [thombashi/sqlitebiter#20]
When first running the script I got this error:

```python
qlitebiter file example.json -o example.sqlite             
Traceback (most recent call last):
  File "/usr/local/bin/sqlitebiter", line 11, in <module>
    sys.exit(cmd())
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 696, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 1060, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.5/dist-packages/click/core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/sqlitebiter/sqlitebiter.py", line 97, in file
    loader = loader_factory.create_from_file_path()
AttributeError: 'TableFileLoaderFactory' object has no attribute 'create_from_file_path'
```
I changed line 97 in /usr/local/lib/python3.5/dist-packages/sqlitebiter/sqlitebiter.py from:
            `loader = loader_factory.create_from_file_path()`
to:
            `loader = loader_factory.create_from_path()
`
... and it worked again

**Comment by thombashi** [comment]
Thank you for your reporting.

Dependency package update caused the problem.

I've fixed the issue with `sqlitebiter 0.3.3`
