### ISSUE TITLE
Error: no such option: --multiprocessing-fork

### ISSUE THREAD

**Issue by chaffinched** [thombashi/sqlitebiter#52]
Hi, on Windows 10 x64 using the binary I get the following:

> sqlitebiter.exe file test.csv
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Error: no such option: --multiprocessing-fork
Traceback (most recent call last):
  File "cli.py", line 12, in <module>
  File "site-packages\click\core.py", line 722, in __call__
  File "site-packages\click\core.py", line 697, in main
  File "site-packages\click\core.py", line 1066, in invoke
  File "site-packages\click\core.py", line 895, in invoke
  File "site-packages\click\core.py", line 535, in invoke
  File "site-packages\click\decorators.py", line 17, in new_func
  File "sqlitebiter\sqlitebiter.py", line 280, in file
  File "site-packages\pytablereader\csv\formatter.py", line 43, in to_table_data
  File "site-packages\tabledata\_core.py", line 123, in __init__
  File "site-packages\dataproperty\_extractor.py", line 358, in to_dp_matrix
  File "site-packages\dataproperty\_extractor.py", line 455, in __to_dp_matrix_mt
  File "concurrent\futures\_base.py", line 425, in result
  File "concurrent\futures\_base.py", line 384, in __get_result
concurrent.futures.process.BrokenProcessPool: A process in the process pool was terminated abruptly while the future was running or pending.
[9248] Failed to execute script cli
Exception ignored in: <bound method SimpleSQLite.__del__ of <simplesqlite.core.SimpleSQLite object at 0x0000021B20EAE2E8>>
Traceback (most recent call last):
  File "site-packages\simplesqlite\core.py", line 109, in __del__
  File "site-packages\simplesqlite\core.py", line 1375, in close
  File "site-packages\simplesqlite\core.py", line 169, in check_connection
  File "site-packages\typepy\_function.py", line 24, in is_null_string
ImportError: sys.meta_path is None, Python is likely shutting down

What am I doing wrong?

**Comment by thombashi** [comment]
@chaffinched 

Thank you for your report.
I had fixed the Windows execution binary at the [latest release](https://github.com/thombashi/sqlitebiter/releases/download/v0.15.1/sqlitebiter_win_x64.zip) 
(Previous versions are wrong the packaging process).
Please try this binary.
