### ISSUE TITLE
Non able to create output, starting from a simple html page

### ISSUE THREAD

**Issue by aborruso** [thombashi/sqlitebiter#87]
# Describe the bug
Hi, when I run

```
sqlitebiter url "https://gist.githubusercontent.com/aborruso/01db63cb74f0646e6bf0cb2b21b02951/raw/220c167e2fd8106f8cfea89d87239a3e8c1d9d6e/page.html"
```

I have this error

```
Traceback (most recent call last):
  File "cli.py", line 14, in <module>
  File "click/core.py", line 1137, in __call__
  File "click/core.py", line 1062, in main
  File "click/core.py", line 1668, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 763, in invoke
  File "click/decorators.py", line 26, in new_func
  File "sqlitebiter/__main__.py", line 433, in url
  File "sqlitebiter/converter/_url.py", line 121, in convert
  File "sqlitebiter/converter/_table_creator.py", line 48, in create
  File "simplesqlite/core.py", line 1378, in create_table_from_tabledata
  File "simplesqlite/core.py", line 1727, in __create_table_from_tabledata
  File "simplesqlite/core.py", line 647, in insert_many
sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.
[14985] Failed to execute script cli
```

# Expected behavior
To have my sqlite db

# To Reproduce

Simply run `sqlitebiter url "https://gist.githubusercontent.com/aborruso/01db63cb74f0646e6bf0cb2b21b02951/raw/220c167e2fd8106f8cfea89d87239a3e8c1d9d6e/page.html"`

# Environments
Please complete the following information:

```
- uname: Linux
- Python version: CPython 3.8.10
- sqlitebiter version: 0.35.2
- SimpleSQLite version: not installed
- pytablereader version: not installed
```

- **Installation Method:** `deb package `

# Additional context
Add any other context (logs, error output, etc.) about the problem here.
(If it’s long, please paste to https://ghostbin.co/ and insert the link here.)

**Comment by thombashi** [comment]
Thank you for your report.


@aborruso 
I believe the problem fixed at `sqlitebiter 0.36.0`.

```
$ sqlitebiter url "https://gist.githubusercontent.com/aborruso/01db63cb74f0646e6bf0cb2b21b02951/raw/220c167e2fd8106f8cfea89d87239a3e8c1d9d6e/page.html"
[INFO] convert 'page.html' to 'html1' table
[INFO] converted results: source=1, success=1, created-table=0
[INFO] database path: out.sqlite
```

Please try to upgrade.

**Comment by aborruso** [comment]
Hi @thombashi first of all thank you very much.

My real input htm file is this big weird one http://sitap.beniculturali.it/info.php
And it gives me `sqlite3.ProgrammingError: Incorrect number of bindings supplied. The current statement uses 2, and there are 1 supplied.`

I have extracted a portion of it (4 tables of 6000) and I have the same error for the third table

```
sqlitebiter url "https://gist.githubusercontent.com/aborruso/85fcf06c1812fdb93b53469907ebd1a5/raw/7ae77be34a8e8e9e423324258538d0a24a3a75f0/tmp.html"
```

**Comment by thombashi** [comment]
@aborruso 
Could you write down more detailed reproduce procedures ?
I could not reproduce the problem with my environment (conversion succeeded):

```
$ sqlitebiter url "https://gist.githubusercontent.com/aborruso/85fcf06c1812fdb93b53469907ebd1a5/raw/7ae77be34a8e8e9e423324258538d0a24a3a75f0/tmp.html"
[INFO] convert 'tmp.html' to 'html1' table
[INFO] convert 'tmp.html' to 'html2' table
[INFO] convert 'tmp.html' to 'html3' table
[INFO] convert 'tmp.html' to 'html4' table
[INFO] converted results: source=1, success=4, created-table=0
[INFO] database path: out.sqlite
```

**Comment by aborruso** [comment]
Hi @thombashi ,
now it works, I have closed and opened again the shell.

Great thank you
